#Built on top Numpy. Python version of R - Data frames or Microsoft Excel

# Pandas Practice

In [0]:
#Series can be accessed by labels
import numpy as np
import pandas as pd

In [488]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}
d

{'a': 10, 'b': 20, 'c': 30}

In [489]:
pd.Series(data=my_data) #indices are 0,1,2

0    10
1    20
2    30
dtype: int64

In [490]:
pd.Series(data=my_data,index=labels) #label the index

a    10
b    20
c    30
dtype: int64

In [491]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [492]:
pd.Series(arr,labels) #Array works same as list

a    10
b    20
c    30
dtype: int64

In [493]:
pd.Series(d) #Python automatically takes the keys as indices

a    10
b    20
c    30
dtype: int64

#Series can store a variety of object types which is also true for almost all complex python data structures

In [494]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [495]:
pd.Series(data=[sum,print,range,len]) #python treats fucntions as first class objects 
#so you can even put built in functions in a series

0      <built-in function sum>
1    <built-in function print>
2              <class 'range'>
3      <built-in function len>
dtype: object

In [496]:
#works just like a hash table or dictionary
ser1 = pd.Series([1,2,3,4],['USA','Germany','USSR','Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [497]:
ser1.dtype

dtype('int64')

In [498]:
ser1['USA'] #name work as index

1

In [499]:
ser3 = pd.Series(labels)
ser3
ser3[1]

'b'

In [0]:
ser2 = pd.Series([1,2,5,4],['USA','Germany','Italy','Japan'])

In [501]:
ser1 + ser2 #Addition occurs on index basis. if index is not found special value NaN is inserted #for operations the values
#gets converted to floats

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

#DataFrames

In [0]:
from numpy.random import randn
np.random.seed(101)

In [503]:
df = pd.DataFrame(randn(5,4))
df

          0         1         2         3
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [504]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z']) #named index
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [505]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [506]:
type(df['W']) #series object

pandas.core.series.Series

In [507]:
type(df) #frame object

pandas.core.frame.DataFrame

In [508]:
df.W #works but not recommended cause overriding methods issue

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [509]:
df[['X','Z']]

          X         Z
A  1.693723 -1.159119
B  0.390528  0.184502
C  0.072960  0.329646
D -0.754070  0.484752
E  1.901755  1.996652

In [510]:
type(df[['X','Z']]) #a data frame

pandas.core.frame.DataFrame

In [0]:
#creating new columns
df['New'] = df["W"] + df["Y"]

In [512]:
df

          W         X         Y         Z       New
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [513]:
#to remove columns 
df.drop('New',axis=1) #axis = 1 refers to columns 
#drop does not affect the df object

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [514]:
df #column still exists

          W         X         Y         Z       New
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [515]:
#to remove permanently use inplace arguemnt 
df.drop('New',axis=1,inplace=True)
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [516]:
df.drop('E') #dropping rows

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

In [517]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [518]:
df.shape #shape is tuple showing 2D matrix mark (0,1) notation (Row,Column)

(5, 4)

In [519]:
#Selecting Rows
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [520]:
df.loc['A']

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [521]:
df.iloc[2]

W    0.807706
X    0.072960
Y    0.638787
Z    0.329646
Name: C, dtype: float64

In [522]:
df.loc['A','W']

0.3026654485851825

In [0]:
#Subsetting

In [524]:
df.iloc[1:3,0:2]

          W         X
B -0.134841  0.390528
C  0.807706  0.072960

In [525]:
df.loc[['A','B'],['W','Z']]

          W         Z
A  0.302665 -1.159119
B -0.134841  0.184502

#Conditional Selection 
#Multi Indexing

In [526]:
df>0 #Returns a boolean data frame

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [527]:
df[df>0] #not very common operation

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [528]:
df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [529]:
df['W'][df['W']>0] #Conditional Row Filtering. Same is conditional operations in sql

A    0.302665
C    0.807706
Name: W, dtype: float64

In [530]:
df.loc[['A'],['Z']][df['Z']>0]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

Empty DataFrame
Columns: [Z]
Index: []

In [531]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [532]:
df[df['Z']<0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119

In [533]:
df[df['W']>0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [0]:
result = df[df['W']>0]

In [535]:
result

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [536]:
result['X']

A    1.693723
C    0.072960
Name: X, dtype: float64

In [537]:
df[df['W']>0]['X']

A    1.693723
C    0.072960
Name: X, dtype: float64

In [538]:
#Mutiple Conditions
#and operation
df[(df['W']>0) & (df['X']>0)] #Use "&" - bit wise and operation not "and" as "and" can evaluate one case at a time not a series

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [539]:
#or operation - same as "and", "|" use this or operator
df[(df['W']>0) | (df['Y']>1)]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [540]:
df.reset_index() #resets index to a column and adds numerical index. but it does not occur inplace so use inplace argument

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [541]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [0]:
df.reset_index(inplace=True)

In [543]:
df

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [544]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [545]:
df['States']=newind
df

  index         W         X         Y         Z States
0     A  0.302665  1.693723 -1.706086 -1.159119     CA
1     B -0.134841  0.390528  0.166905  0.184502     NY
2     C  0.807706  0.072960  0.638787  0.329646     WY
3     D -0.497104 -0.754070 -0.943406  0.484752     OR
4     E -0.116773  1.901755  0.238127  1.996652     CO

In [0]:
df.set_index('States',inplace=True)

In [547]:
df['Name'] = df['index']
df.drop('Name',axis=1,inplace=True)
df

       index         W         X         Y         Z
States
CA         A  0.302665  1.693723 -1.706086 -1.159119
NY         B -0.134841  0.390528  0.166905  0.184502
WY         C  0.807706  0.072960  0.638787  0.329646
OR         D -0.497104 -0.754070 -0.943406  0.484752
CO         E -0.116773  1.901755  0.238127  1.996652

In [548]:
#Multi Level Index
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside)) #combine two lists
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [549]:
hier_index = pd.MultiIndex.from_tuples(hier_index) #create levels and level labels 
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [550]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])
df #Index Hierarchy

             A         B
G1 1 -0.993263  0.196800
   2 -1.136645  0.000366
   3  1.025984 -0.156598
G2 1 -0.031579  0.649826
   2  2.154846 -0.610259
   3 -0.755325 -0.346419

In [551]:
df.loc['G1'].loc[1]

A   -0.993263
B    0.196800
Name: 1, dtype: float64

In [552]:
df.loc['G1']

          A         B
1 -0.993263  0.196800
2 -1.136645  0.000366
3  1.025984 -0.156598

In [553]:
df.index.names

FrozenList([None, None])

In [554]:
df.index.names = ['Groups','Num']
df

                   A         B
Groups Num
G1     1   -0.993263  0.196800
       2   -1.136645  0.000366
       3    1.025984 -0.156598
G2     1   -0.031579  0.649826
       2    2.154846 -0.610259
       3   -0.755325 -0.346419

In [555]:
df.loc['G2'].loc[2]['B']

-0.6102588558227414

In [556]:
df.loc['G1'].loc[1]['A']

-0.993263499973366

In [557]:
df.xs('G1') #returns a crossection of data for multilevel index

            A         B
Num
1   -0.993263  0.196800
2   -1.136645  0.000366
3    1.025984 -0.156598

In [558]:
df.xs(1,level='Num') #grab a cross section from both the groups

               A         B
Groups
G1     -0.993263  0.196800
G2     -0.031579  0.649826

# Manage Missing Data

In [559]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [560]:
df = pd.DataFrame(d)
df #Nans are missing values

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [561]:
df.dropna() # drops rows with Nan

     A    B  C
0  1.0  5.0  1

In [562]:
df.dropna(axis=1) #drops columns with Nan

   C
0  1
1  2
2  3

In [563]:
df #remember no inplace change

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [564]:
#specify threshold 
df.dropna(thresh=2) #drops any row with two or more non NaN values

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [565]:
#Replacing missing values
df.fillna(value=df.mean()) #feeding mean of dataframe

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [566]:
df['A'].fillna(value=df['A'].mean()) #feeding feature wise mean

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

#Grouping in DataFrames

In [567]:
data = {'Company':['Goog','Goog','Msft','Msft','Fb','Fb'], 'Person':['Srikanth','Amit','Suhwan','Mandy','Milo','Pooja'],
       'Sales':[200,100,340,124,243,350]}
data

{'Company': ['Goog', 'Goog', 'Msft', 'Msft', 'Fb', 'Fb'],
 'Person': ['Srikanth', 'Amit', 'Suhwan', 'Mandy', 'Milo', 'Pooja'],
 'Sales': [200, 100, 340, 124, 243, 350]}

In [568]:
df = pd.DataFrame(data)
df

  Company    Person  Sales
0    Goog  Srikanth    200
1    Goog      Amit    100
2    Msft    Suhwan    340
3    Msft     Mandy    124
4      Fb      Milo    243
5      Fb     Pooja    350

In [569]:
#group by compnay
df.groupby('Company') #creates group by object

In [570]:
df.groupby('Company').mean()

         Sales
Company
Fb       296.5
Goog     150.0
Msft     232.0

In [571]:
df.groupby('Company').std()

              Sales
Company
Fb        75.660426
Goog      70.710678
Msft     152.735065

In [572]:
df.groupby('Company').var()

           Sales
Company
Fb        5724.5
Goog      5000.0
Msft     23328.0

In [573]:
df.groupby('Company').sum().loc['Fb'] #sum of fb sales

Sales    593
Name: Fb, dtype: int64

In [574]:
df.groupby('Company').count()

         Person  Sales
Company
Fb            2      2
Goog          2      2
Msft          2      2

In [575]:
df.groupby('Company').describe() #Gives statistical info

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
Fb        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
Goog      2.0  150.0   70.710678  100.0  125.00  150.0  175.00  200.0
Msft      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [576]:
df.groupby('Company').describe().transpose()

Company              Fb        Goog        Msft
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  150.000000  232.000000
      std     75.660426   70.710678  152.735065
      min    243.000000  100.000000  124.000000
      25%    269.750000  125.000000  178.000000
      50%    296.500000  150.000000  232.000000
      75%    323.250000  175.000000  286.000000
      max    350.000000  200.000000  340.000000

# Meging, Joining and Concatneting

In [0]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [578]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [579]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [580]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [581]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [582]:
pd.concat([df1,df2,df3],axis=1) #concat across axis. will create NaN values to fill empty positions. Observe the pattern

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [0]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [584]:
left, right

(    A   B key
 0  A0  B0  K0
 1  A1  B1  K1
 2  A2  B2  K2
 3  A3  B3  K3,     C   D key
 0  C0  D0  K0
 1  C1  D1  K1
 2  C2  D2  K2
 3  C3  D3  K3)

In [585]:
#Merging dfs
pd.merge(left,right,how="inner",on="key") #similar to sql joins. "how" defines type of join, "on" defines constraint columns

    A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [0]:
left1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right1 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [587]:
pd.merge(left1,right1,how='inner',on=['key1','key2']) #merge using 2 features

    A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [588]:
pd.merge(left1,right1,how='outer',on=['key1','key2'])

     A    B key1 key2    C    D
0   A0   B0   K0   K0   C0   D0
1   A1   B1   K0   K1  NaN  NaN
2   A2   B2   K1   K0   C1   D1
3   A2   B2   K1   K0   C2   D2
4   A3   B3   K2   K1  NaN  NaN
5  NaN  NaN   K2   K0   C3   D3

In [0]:
left2 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right2 = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [590]:
#joining
left2.join(right2) #uses the index feature instead of keys to merge two data frames

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [591]:
left2.join(right2,how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

# Opreations

In [592]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()
df.tail()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [593]:
df['col2'].nunique() #find number of unique values

3

In [594]:
df['col2'].unique() #find unique values in col2

array([444, 555, 666])

In [595]:
df['col2'].value_counts() #no. of occurence

444    2
555    1
666    1
Name: col2, dtype: int64

In [596]:
df[df['col1']>2]

   col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [597]:
df[(df['col1']>2)&(df['col2']==444)]

   col1  col2 col3
3     4   444  xyz

In [0]:
def times2(x):
    return x*2

In [599]:
df['col1'].apply(times2) #using function

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [600]:
df['col1'].apply(lambda x:x*2) #using annonymous functions

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [601]:
df['col3'].apply(len) #applying built in func

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [602]:
#remove col
df.drop('col1',axis=1) #not inplace ops

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [603]:
df.columns #info abt features

Index(['col1', 'col2', 'col3'], dtype='object')

In [604]:
df.index #info abt index

RangeIndex(start=0, stop=4, step=1)

In [605]:
df.sort_values('col2') #sorting by col

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [606]:
df.sort_values('col2')

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [607]:
df.isnull()

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [0]:
#Pivoting dataframes
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [609]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [610]:
df.pivot_table(values='D',index=['A','B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [611]:
pwd

'/content'

In [612]:
pd.read_csv('example')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [0]:
df = pd.read_csv('example')
df.to_csv('my_op',index=False)

In [614]:
pd.read_csv('my_op')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [615]:
pd.read_excel('Excel_Sample.xlsx')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [0]:
df=pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

In [0]:
df.to_excel('my_op2.xlsx',sheet_name='NewSheet')

In [0]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [619]:
df[0].head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Washington Federal Bank for Savings,Chicago,IL,30570,Royal Savings Bank,"December 15, 2017","February 21, 2018"
1,The Farmers and Merchants State Bank of Argonia,Argonia,KS,17719,Conway Bank,"October 13, 2017","February 21, 2018"
2,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb","May 26, 2017","July 26, 2017"
3,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,"May 5, 2017","March 22, 2018"
4,First NBC Bank,New Orleans,LA,58302,Whitney Bank,"April 28, 2017","December 5, 2017"

In [0]:
from sqlalchemy import create_engine

In [0]:
engine = create_engine("sqlite:///:memory:") #creates in memory sql enigne

In [622]:
df = pd.read_csv('example')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [0]:
df.to_sql('my_table',engine)

In [0]:
sqldf = pd.read_sql('my_table',con=engine)

In [625]:
sqldf

   index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15

# Working with Real World Data

#get the 'SF Salaries' dataset from Kaggle - Make sure you place the file in same directory as notebook or give the full path

In [626]:
sal = pd.read_csv('Salaries.csv')
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011.0,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011.0,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011.0,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0,NaN,San Francisco,NaN

In [627]:
pwd

'/content'

In [628]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19923 entries, 0 to 19922
Data columns (total 13 columns):
Id                  19923 non-null int64
EmployeeName        19923 non-null object
JobTitle            19922 non-null object
BasePay             19922 non-null float64
OvertimePay         19922 non-null float64
OtherPay            19922 non-null float64
Benefits            0 non-null float64
TotalPay            19922 non-null float64
TotalPayBenefits    19922 non-null float64
Year                19922 non-null float64
Notes               0 non-null float64
Agency              19922 non-null object
Status              0 non-null float64
dtypes: float64(9), int64(1), object(3)
memory usage: 2.0+ MB

In [629]:
sal.BasePay.mean()
#sal['BasePay'].mean()

92255.34896948097

In [630]:
sal.OvertimePay.max()

245131.88

In [631]:
sal['JobTitle'][sal['EmployeeName']=="JOSEPH DRISCOLL"]
sal.JobTitle[sal.EmployeeName=="JOSEPH DRISCOLL"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [632]:
sal.TotalPayBenefits[sal.EmployeeName=="JOSEPH DRISCOLL"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [633]:
sal[sal['TotalPayBenefits']==sal.TotalPayBenefits.max()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN

In [634]:
sal.loc[sal['TotalPayBenefits'].idxmax()] #Smililar to Numpy argmax

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                     167411
OvertimePay                                                      0
OtherPay                                                    400184
Benefits                                                       NaN
TotalPay                                                    567595
TotalPayBenefits                                            567595
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

In [635]:
sal.iloc[sal['TotalPayBenefits'].values.argmax()] #correct way

Id                            19923
EmployeeName        DIMITRI SHIKALO
JobTitle                        NaN
BasePay                         NaN
OvertimePay                     NaN
OtherPay                        NaN
Benefits                        NaN
TotalPay                        NaN
TotalPayBenefits                NaN
Year                            NaN
Notes                           NaN
Agency                          NaN
Status                          NaN
Name: 19922, dtype: object

In [636]:
sal[sal.TotalPayBenefits==sal.TotalPayBenefits.min()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
19921,19922,CHARLES BRIDGEWATER,ASPHALT WORKER,57408.59,3227.92,2898.46,NaN,63534.97,63534.97,2011.0,NaN,San Francisco,NaN

In [637]:
sal.iloc[sal['TotalPayBenefits'].values.argmin()]

Id                            19923
EmployeeName        DIMITRI SHIKALO
JobTitle                        NaN
BasePay                         NaN
OvertimePay                     NaN
OtherPay                        NaN
Benefits                        NaN
TotalPay                        NaN
TotalPayBenefits                NaN
Year                            NaN
Notes                           NaN
Agency                          NaN
Status                          NaN
Name: 19922, dtype: object

In [638]:
sal.groupby('Year').mean()['BasePay']
sal.groupby('Year').mean().BasePay

Year
2011.0    92255.348969
Name: BasePay, dtype: float64

In [639]:
sal.JobTitle.nunique()

870

In [640]:
sal.groupby('JobTitle').JobTitle.count().sort_values(ascending=False).head()

JobTitle
TRANSIT OPERATOR      1463
REGISTERED NURSE      1082
FIREFIGHTER            744
POLICE OFFICER III     743
DEPUTY SHERIFF         653
Name: JobTitle, dtype: int64

In [641]:
sal['JobTitle'].value_counts().head(5) #better way to do

TRANSIT OPERATOR      1463
REGISTERED NURSE      1082
FIREFIGHTER            744
POLICE OFFICER III     743
DEPUTY SHERIFF         653
Name: JobTitle, dtype: int64

In [642]:
c1=0
for i,j in sal.groupby(['Year','JobTitle']).JobTitle.count().iteritems():
    if i[0]==2013 and j ==1:
        c1+=1
c1

0

In [643]:
sum([1 for i,j in sal.groupby(['Year','JobTitle']).JobTitle.count().iteritems()  if i[0]==2013 and j ==1])

0

In [644]:
sum(sal[sal['Year']==2013]['JobTitle'].value_counts()==1)

0

In [648]:
'''b=0
for i in sal['JobTitle']:
    if i.upper().find('CHIEF') == 0:
        b=b+1
print(b)
sal['JobTitle']
type(sal['JobTitle'])'''
#counts all the cases of chief 
c2=0
for i,r in sal.JobTitle.iteritems():
    if 'Chief'.upper() in str(r).upper():
        c2 +=1
c2

190

In [654]:
sum([1 for i,r in sal.JobTitle.iteritems() if 'Chief'.upper() in str(r).upper()]) #same code in one line

190

In [0]:
def chf(x):
    if 'chief' in str(x).lower().split(): return True
    else: return False

In [658]:
sum(sal['JobTitle'].apply(lambda x:chf(x))) #gives sum of all True but ignores punctuated cases of chief

145

In [0]:
#sal['TitleLength'] = sal['JobTitle'].apply(len) 
#sal.head()

In [0]:
#sal.TotalPayBenefits.corr(sal.TitleLength) #gives corr coefficient value
#sal[['TotalPayBenefits','TitleLength']].corr() #gives corr table

In [672]:
sal.corr()

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Status
Id,1.000000,-0.828425,-0.330922,-0.414635,NaN,-0.932111,-0.932111,NaN,NaN,NaN
BasePay,-0.828425,1.000000,-0.067782,0.140669,NaN,0.839597,0.839597,NaN,NaN,NaN
OvertimePay,-0.330922,-0.067782,1.000000,0.269653,NaN,0.409247,0.409247,NaN,NaN,NaN
OtherPay,-0.414635,0.140669,0.269653,1.000000,NaN,0.511989,0.511989,NaN,NaN,NaN
Benefits,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TotalPay,-0.932111,0.839597,0.409247,0.511989,NaN,1.000000,1.000000,NaN,NaN,NaN
TotalPayBenefits,-0.932111,0.839597,0.409247,0.511989,NaN,1.000000,1.000000,NaN,NaN,NaN
Year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Status,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [663]:
pd.DataFrame.info(sal[['JobTitle']])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19923 entries, 0 to 19922
Data columns (total 1 columns):
JobTitle    19922 non-null object
dtypes: object(1)
memory usage: 155.7+ KB